apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000  # Elasticsearch의 UID/GID에 맞는 값으로 설정
      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-storage
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
              name: elasticsearch-port-9200  # 이름 추가
            - containerPort: 9300
              name: elasticsearch-port-9300  # 이름 추가
      nodeSelector:
        purpose: custom
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: dev
spec:
  ports:
    - port: 9200
      targetPort: 9200
      name: elasticsearch-port-9200  # 이름 추가
    - port: 9300
      targetPort: 9300
      name: elasticsearch-port-9300  # 이름 추가
  selector:
    app: elasticsearch
