apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers: # Init Container 추가
        - name: install-plugins
          image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
          command:
            - sh
            - -c
            - |
              elasticsearch-plugin install --batch analysis-nori
              chown -R 1000:1000 /usr/share/elasticsearch/plugins
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/plugins
              name: elasticsearch-plugins
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
              name: es-port-9200  # 이름 추가
            - containerPort: 9300
              name: es-port-9300  # 이름 추가
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
        - name: elasticsearch-plugins  # 플러그인 저장용 볼륨 추가
          emptyDir: {}
      nodeSelector:
        purpose: custom
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: dev
spec:
  ports:
    - port: 9200
      targetPort: 9200
      name: es-port-9200  # 이름 추가
    - port: 9300
      targetPort: 9300
      name: es-port-9300  # 이름 추가
  selector:
    app: elasticsearch
