apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-secret
  namespace: dev
spec:
  secretStoreRef:            # Secret을 가져올 SecretStore 작성
    name: aws-secretmanager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: aws-secrets-manager-db-config    # 가져온 값으로 클러스터에 생성할 Secret object의 이름
  data:
    - secretKey: mariadb.host
      remoteRef:             # Secrets Manager에 저장된 Secret
        key: medihub/dev/db-config
        property: mariadb.host
    - secretKey: mariadb.port
      remoteRef:
        key: medihub/dev/db-config
        property: mariadb.port
    - secretKey: db.name
      remoteRef:
        key: medihub/dev/db-config
        property: db.name
    - secretKey: db.password
      remoteRef:
        key: medihub/dev/db-config
        property: db.password
    - secretKey: mongodb.host
      remoteRef:
        key: medihub/dev/db-config
        property: mongodb.host
    - secretKey: mongodb.port
      remoteRef:
        key: medihub/dev/db-config
        property: mongodb.port
    - secretKey: redis.host
      remoteRef:
        key: medihub/dev/db-config
        property: redis.host
    - secretKey: redis.port
      remoteRef:
        key: medihub/dev/db-config
        property: redis.port