apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
              name: kafka-9092  # 이름 수정 (15자 이하)
            - containerPort: 9093
              name: kafka-9093  # 이름 수정 (15자 이하)
            - containerPort: 10000
              name: kafka-10000  # 이름 수정 (15자 이하)
          env:
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:10000"
      nodeSelector:
        purpose: custom
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: dev
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka-9092  # 이름 수정 (15자 이하)
    - port: 10000
      targetPort: 10000
      name: kafka-10000  # 이름 수정 (15자 이하)
  selector:
    app: kafka
