apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.14.1
          env:
            - name: SERVER_NAME
              value: kibana
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
          ports:
            - containerPort: 5601
      nodeSelector:
        purpose: custom
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: dev
spec:
  ports:
    - port: 5601
  selector:
    app: kibana
