apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.14.1
          ports:
            - containerPort: 5000
              name: logstash-port-5000  # 이름 추가
            - containerPort: 9600
              name: logstash-port-9600  # 이름 추가
      nodeSelector:
        purpose: custom
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: dev
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: logstash-port-5000  # 이름 추가
    - port: 9600
      targetPort: 9600
      name: logstash-port-9600  # 이름 추가
  selector:
    app: logstash
