apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
      containers:
        - name: mongodb
          image: mongo:latest
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager-db-config
                  key: db.name
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager-db-config
                  key: db.name
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager-db-config
                  key: db.password
          ports:
            - containerPort: 27017