apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-redis
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-redis
  template:
    metadata:
      labels:
        app: session-redis
    spec:
      containers:
        - name: session-redis
          image: redis:alpine
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager-db-config
                  key: db.password
          ports:
            - containerPort: 6379
          command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
      nodeSelector:
        purpose: custom