apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager-db-config
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "medihub/dev/db-config"
        objectType: "secretsmanager"

---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager-openai-config
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "medihub/dev/openai-config"
        objectType: "secretsmanager"

---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager-s3-config
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "medihub/dev/s3-config"
        objectType: "secretsmanager"

---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager-elasticsearch-config
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "medihub/dev/elasticsearch-config"
        objectType: "secretsmanager"

---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager-other-config
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "medihub/dev/other-config"
        objectType: "secretsmanager"

---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager-newsapi-config
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "medihub/dev/newsapi-config"
        objectType: "secretsmanager"
