#apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
#kind: SecretProviderClass
#metadata:
#  name: aws-secrets-manager-db-config
#  namespace: dev
#spec:
#  provider: aws
#  parameters:
#    objects: |
#      - objectName: "medihub/dev/db-config"
#        objectType: "secretsmanager"
#        jmesPath:
#          - path: mariadb.host
#            objectAlias: mariadb.host
#          - path: mariadb.port
#            objectAlias: mariadb.port
#          - path: db.name
#            objectAlias: db.name
#          - path: db.password
#            objectAlias: db.password
#          - path: mongodb.host
#            objectAlias: mongodb.host
#          - path: mongodb.port
#            objectAlias: mongodb.port
#          - path: redis.host
#            objectAlias: redis.host
#          - path: redis.port
#            objectAlias: redis.port
#  secretObjects:
#    - secretName: aws-secrets-manager-db-config
#      type: Opaque
#      data:
#        - objectName: mariadb.host
#          key: mariadb.host
#        - objectName: mariadb.port
#          key: mariadb.port
#        - objectName: db.name
#          key: db.name
#        - objectName: db.password
#          key: db.password
#        - objectName: mongodb.host
#          key: mongodb.host
#        - objectName: mongodb.port
#          key: mongodb.port
#        - objectName: redis.host
#          key: redis.host
#        - objectName: redis.port
#          key: redis.port
#
#---
#apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
#kind: SecretProviderClass
#metadata:
#  name: aws-secrets-manager-openai-config
#  namespace: dev
#spec:
#  provider: aws
#  parameters:
#    objects: |
#      - objectName: "medihub/dev/openai-config"
#        objectType: "secretsmanager"
#        jmesPath:
#          - path: openai.api.key
#            objectAlias: openai.api.key
#          - path: openai.model
#            objectAlias: openai.model
#          - path: openai.api.url
#            objectAlias: openai.api.url
#          - path: openai.api.key.bot
#            objectAlias: openai.api.key.bot
#  secretObjects:
#    - secretName: aws-secrets-manager-openai-config
#      type: Opaque
#      data:
#        - objectName: openai.api.key
#          key: openai.api.key
#        - objectName: openai.model
#          key: openai.model
#        - objectName: openai.api.url
#          key: openai.api.url
#        - objectName: openai.api.key.bot
#          key: openai.api.key.bot
#
#---
#
#apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
#kind: SecretProviderClass
#metadata:
#  name: aws-secrets-manager-s3-config
#  namespace: dev
#spec:
#  provider: aws
#  parameters:
#    objects: |
#      - objectName: "medihub/dev/s3-config"
#        objectType: "secretsmanager"
#        jmesPath:
#          - path: s3.credentials.access-key
#            objectAlias: s3.credentials.access-key
#          - path: s3.credentials.secret-key
#            objectAlias: s3.credentials.secret-key
#          - path: s3.credentials.region
#            objectAlias: s3.credentials.region
#          - path: s3.bucket
#            objectAlias: s3.bucket
#  secretObjects:
#    - secretName: aws-secrets-manager-s3-config
#      type: Opaque
#      data:
#        - objectName: s3.credentials.access-key
#          key: s3.credentials.access-key
#        - objectName: s3.credentials.secret-key
#          key: s3.credentials.secret-key
#        - objectName: s3.credentials.region
#          key: s3.credentials.region
#        - objectName: s3.bucket
#          key: s3.bucket
#
#---
#apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
#kind: SecretProviderClass
#metadata:
#  name: aws-secrets-manager-elasticsearch-config
#  namespace: dev
#spec:
#  provider: aws
#  parameters:
#    objects: |
#      - objectName: "medihub/dev/elasticsearch-config"
#        objectType: "secretsmanager"
#        jmesPath:
#          - path: elastic_uris
#            objectAlias: elastic_uris
#          - path: elastic_user
#            objectAlias: elastic_user
#          - path: elastic_password
#            objectAlias: elastic_password
#  secretObjects:
#    - secretName: aws-secrets-manager-elasticsearch-config
#      type: Opaque
#      data:
#        - objectName: elastic_uris
#          key: elastic_uris
#        - objectName: elastic_user
#          key: elastic_user
#        - objectName: elastic_password
#          key: elastic_password
#
#---
#apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
#kind: SecretProviderClass
#metadata:
#  name: aws-secrets-manager-other-config
#  namespace: dev
#spec:
#  provider: aws
#  parameters:
#    objects: |
#      - objectName: "medihub/dev/other-config"
#        objectType: "secretsmanager"
#        jmesPath:
#          - path: SECRET_KEY
#            objectAlias: SECRET_KEY
#          - path: user.default-password
#            objectAlias: user.default-password
#  secretObjects:
#    - secretName: aws-secrets-manager-other-config
#      type: Opaque
#      data:
#        - objectName: SECRET_KEY
#          key: SECRET_KEY
#        - objectName: user.default-password
#          key: user.default-password
#
#---
#apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
#kind: SecretProviderClass
#metadata:
#  name: aws-secrets-manager-newsapi-config
#  namespace: dev
#spec:
#  provider: aws
#  parameters:
#    objects: |
#      - objectName: "medihub/dev/newsapi-config"
#        objectType: "secretsmanager"
#        jmesPath:
#          - path: newsapi.api-key
#            objectAlias: newsapi.api-key
#          - path: newsapi.base-url
#            objectAlias: newsapi.base-url
#  secretObjects:
#    - secretName: aws-secrets-manager-newsapi-config
#      type: Opaque
#      data:
#        - objectName: newsapi.api-key
#          key: newsapi.api-key
#        - objectName: newsapi.base-url
#          key: newsapi.base-url